#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
echo "Holberton School for the win" | sudo tee /usr/share/nginx/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
redirect="\n\tlocation /redirect_me {\n\t\treturn http://www.koome.tech;\n\t}\n"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default
sudo service nginx start

