#!/usr/bin/env bash
# Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02, manage script via init file
sudo apt-get update
sudo apt-get install -y haproxy=1.5\*
sudo cp /etc/default/haproxy /etc/default/haproxy.bak
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.bak
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

# Round Robin - selects servers in turns. It is the default algorithm
config="frontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tmode http\n\toption forwardfor\n\tserver 698-web-01 34.73.218.30:80 check\n\tserver 698-web-02 35.196.224.3:80 check\n"
echo -e $config | tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy reload
sudo service haproxy restart
