#!/usr/bin/env bash
# Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02, manage script via init file
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
printf "\nfrontend haproxynode
	bind *:80
	mode http
	default_backend backendnodes
backend backendnodes
	balance roundrobin
	server 698-web-01 34.73.218.30:80 check
	server 698-web-02 35.196.224.3:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy reload
service haproxy restart
