#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

file=/etc/passwd

while read -r user;
do
	username=$(echo "$user" | cut -d: -f1)
	uid=$(echo "$user" | cut -d: -f3)
	home=$(echo "$user" | cut -d: -f6)

	echo "$username:$uid:$home"
done < "$file"
