#!/usr/bin/env bash
# Bash script that loops from 1 to 10 using while, if, elif else

n=0
while [ $n -lt 10 ]
do

	(( n++ ))
     	if [ $n == 4 ]
     	then
		echo "bad luck"
     	elif [ $n == 8 ]
     	then
		echo "good luck"
     	else
     		echo "Holberton School"
	fi
done
