#!/usr/bin/env bash

n=1
while [ $n -lt 21 ]
do
	printf "%s$n\n"
	if [ $n == 4 ]
	then
		echo "bad luck from China"
	elif [ $n == 9 ]
	then
		echo "bad luck from Japan"
	elif [ $n == 17 ]
	then
		echo "bad luck from Italy"
	fi
	((n++))
done
