#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file

FILE=holbertonschool

if [ -f "$FILE" ]; then
	echo "$FILE file exists"
else
	echo "$FILE file does not exist"
fi
if [ -s "$FILE" ];
then
	echo "$FILE file is not empty"
else
	echo "$FILE file is empty"
fi
if [ ! -d "$FILE" ];
then
	echo "$FILE is a regular file"
fi

