#!/usr/bin/env bash
# Refactored script to run nginx as the nginx user
chmod 755 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
