#!/usr/bin/env bash
# Refactored script to run nginx as the nginx user
pkill apache2
chmod 755 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
